/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: AnshiNoWara (https://sketchfab.com/AnshiNoWara)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/c-1b277fc32bbc451fa6f40e298996ba91
Title: C++
*/
import {Float, useGLTF} from '@react-three/drei'

const CppLogo = (props) => {
    const { nodes, materials } = useGLTF('/models/c.glb')
    return (
        <Float floatIntensity={1}>
            <group {...props} dispose={null}>
                <group scale={0.0003}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes['C++_C++_0'].geometry}
                        material={materials.material}
                        position={[0, 0, 199.569]}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}
                    />
                </group>
            </group>
        </Float>
    )
}

useGLTF.preload('/models/c.glb')
export default CppLogo;



